create table SYS_USER (
	user_id int generated by default as identity (start with 1 increment by 1) not null,
	user_name varchar(64) not null,
	password varchar(256) not null,
	enabled boolean not null,
  online boolean not null,
	primary key (user_id)
);

create table SYS_USER_ROLE (
	role_id int generated by default as identity (start with 1 increment by 1) not null,
  user_id int not null,
	role_name varchar(128) not null,
	primary key (role_id)
);

create table SYS_POST (
  post_id int generated by default as identity (start with 1 increment by 1) not null,
  post_title varchar(128) not null,
  post_content VARCHAR(1024) not null,
  user_id int not null,
  post_time timestamp not null,
  last_modified_time timestamp not null
);

create table SYS_PREVILEDGES (
	previledge_id int not null,
	previledge_name varchar(128) not null,
	primary key (previledge_id)
);

create table ROLE_PREVILEDGES (
	role_id int not null,
	previledge_id int not null,
	primary key (role_id, previledge_id)
);

alter table SYS_USER add constraint UNIQUE_SYS_USER_NAME unique (user_name);

alter table SYS_USER_ROLE add constraint FK_SYS_USER_ROLE_USER_ID foreign key (user_id) references SYS_USER (user_id);

alter table SYS_POST add constraint  FK_SYS_POSTS_USER_ID foreign key (user_id) references SYS_USER (user_id);

insert into SYS_PREVILEDGES (previledge_id, previledge_name) values (1, 'PREVILEDGE_ALL');
insert into SYS_PREVILEDGES (previledge_id, previledge_name) values (2, 'PREVILEDGE_READ_ONLY');

insert into ROLE_PREVILEDGES (role_id, previledge_id) values (1, 1);
insert into ROLE_PREVILEDGES (role_id, previledge_id) values (2, 2);

insert into SYS_USER (user_id, user_name, password, enabled, online) values (default, 'Admin', 'test', true, false);
insert into SYS_USER (user_id, user_name, password, enabled, online) values (default, 'tester', 'test', true, false);

insert into SYS_USER_ROLE (role_id, user_id, role_name) values (default, 1, 'ROLE_ADMIN');
insert into SYS_USER_ROLE (role_id, user_id, role_name) values (default, 1, 'ROLE_USER');
insert into SYS_USER_ROLE (role_id, user_id, role_name) values (default, 2, 'ROLE_USER');

insert into SYS_POST (post_id, post_title, post_content, user_id, post_time, last_modified_time) values (default, 'Welcome', 'Welcome to the User Management System', 1, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP);
insert into SYS_POST (post_id, post_title, post_content, user_id, post_time, last_modified_time) values (default, '11111111111111111111MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMa long title example', '.........................................................\n.................................................\nA really long content example...................................', 1, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP);